import torch
 
 # load the model
model_path = "megaDNA_phage_145M.pt"
device = 'cuda' # use 'cuda' for GPU
model = torch.load(model_path, map_location=torch.device(device), weights_only=False)

# new sequences can be generated by a primer sequence:
primer_sequence = "ACTGTACGT"
context_length = 10
nucleotides = ['**', 'A', 'T', 'C', 'G', '#'] # vocabulary

seq_tokenized = model.generate(primer_sequence,
                            seq_len=context_length,
                            temperature=0.95, 
                            filter_thres=0.0)

# To transform tokens back to DNA ucleotide sequence:
def token2nucleotide(s):
    return nucleotides[s]
generated_sequence = ''.join(map(token2nucleotide, seq_tokenized.squeeze().cpu().int()))